from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(slots=True)
class TelegramBridgeError(Exception):
    code: str
    message: str
    details: Any = None

    def __str__(self) -> str:
        return self.message


NOT_AUTHORIZED = "NOT_AUTHORIZED"
CHAT_NOT_FOUND = "CHAT_NOT_FOUND"
AMBIGUOUS_CHAT = "AMBIGUOUS_CHAT"
MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
FLOOD_WAIT = "FLOOD_WAIT"
WRITE_FAILED = "WRITE_FAILED"
INVALID_ARGUMENT = "INVALID_ARGUMENT"
SESSION_BUSY = "SESSION_BUSY"
UNSUPPORTED_MESSAGE = "UNSUPPORTED_MESSAGE"

# v0.2.0 daemon / IPC errors.
DAEMON_UNAVAILABLE = "DAEMON_UNAVAILABLE"
DAEMON_UPGRADE_REQUIRED = "DAEMON_UPGRADE_REQUIRED"
IPC_PROTOCOL_ERROR = "IPC_PROTOCOL_ERROR"
IPC_RESPONSE_TOO_LARGE = "IPC_RESPONSE_TOO_LARGE"
EXPORT_IN_PROGRESS = "EXPORT_IN_PROGRESS"
WRITE_OUTCOME_UNKNOWN = "WRITE_OUTCOME_UNKNOWN"
AUTH_GUI_ONLY = "AUTH_GUI_ONLY"

# v0.3.0 personal-account reader errors.
INVALID_CURSOR = "INVALID_CURSOR"
CURSOR_STALE = "CURSOR_STALE"
ACCESS_DENIED = "ACCESS_DENIED"
MEMBERS_UNAVAILABLE = "MEMBERS_UNAVAILABLE"
NOT_A_FORUM = "NOT_A_FORUM"
DOWNLOAD_CONFIRMATION_REQUIRED = "DOWNLOAD_CONFIRMATION_REQUIRED"
DOWNLOAD_LIMIT_EXCEEDED = "DOWNLOAD_LIMIT_EXCEEDED"
